language: python
python:
  - 2.7
#  - "3.3" one day!
# no virtualenv
#virtualenv:
#  system_site_packages: false
 
# Setup anaconda
before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

# Install packages
install:
  - conda create --quiet --yes -n buildenv python=$TRAVIS_PYTHON_VERSION
  - source activate buildenv
  - conda install --yes numpy scipy matplotlib sympy nose setuptools
  - conda install --yes -c dan_blanchard python-coveralls nose-cov
  - python setup.py install
 
# Run the tests
script: nosetests -v -s --with-coverage --cover-package=ahkab tests/*/*.py
 
# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc

